sudo: required
dist: trusty
language: node_js
node_js: '8'
os:
- linux
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
install:
- npm i
script:
- gulp
- npm run dist
deploy:
  provider: releases
  api_key:
    secure: Dj/Tc7O/anLe0l5zLdT1qPnz/EdbEwDq6jqtRtndP9QzrbCf05EYJEI8qjggLk2qKfLfXzLvFJk10EL3SUB5Ehd/wW2o2xUKV9Ov766OoM7jyitnH7J/uocNn/ZzXl5Q2b0mPSE970y9k+asdyyHMALQboHNp5EbHKekVaq+45gM1MBEoDp5cbpNQEW0itFgT+fFY4TUrSjPzaNoxE3TUbzBF+UGdaxmV8w/TjOJCcRmavKoHGC5QHfdMgGOgofcgdD9w6MTQxc1RMAJLx1LCC5/jKkXGZmNrZ8pkEz8W9R+2R1D6J9HZPg0pBKHuoW2h26+41Cts6UZLkZlpkT1heay/XALztLezLGiNTO8QHFG9shPObK1064DW/a7uCt5fa7yH7EuzgMb3EEeCjEdTX3jQC50RycvKSTie4hhH34mF9BxQjhqnKGzV/5KSgDQPs/FWHiBSft5Nc+0VEGhVncxPk7IJKSCgNaKRtlMVV+XflTgpWB1Z3n3b37NC69VwVJbdvfXqhZq+clDISCGFkirxJclZn3+nNU2REp5vuqDXn4JOi7NzabSlzeehGos343gIK8YYd0mIMMCyWfPlHv3PrJD9I2QTNjyKrq2suBBDG0Xj5FEoFGX6eCnarMn22mx1Cb2/Gsg63eEmryHEND4zQvzdh2/Y+XYQrAnZ9w=
  file:
  - dist/meistertask-electron-1.0.2-x86_64.AppImage
  - dist/meistertask-electron_1.0.2_amd64.deb
  skip_cleanup: true
  on:
    repo: ClocxHD/MeisterTask-Electron
    tags: true
notifications:
  slack:
    secure: CtFcAnXoiJcNIL8bDT9rWuT1vKb9Jomi//vMbdPlfZLFNJdWwvzoTNdNli4nwuhptvkfMz8L2SpDNE9rAylkNygXoUoB5SYMW174fwPza7m1LFsl5XG7kEFsz3Lj7wQDOL0zvpny2hzxVUQcqxVGphLKu7f09Q1VKtmO+dTe5dsBADtBQEL9mjDL71Bwnv3BgV+ldL2C0t3WSapm6Wr++ddHr3ivn9CRzeaUpHjqHUXjFKNQEhT5efLL4XptoMLl31n8SqRiaXl1BM45SkOu8DGPW87XV6V4WLDKt4Rwwfxsqqm8yE3D9tXw4Q/YU9lJQT9aec4Y/gnD+BCZpjSc1f3u2xoe3joEAxkfN6gHImZbv9cBJ9F+Ab+aAWiV/ttfJj+zwFm5zLPFeWGMXk0MWfD6JXJPCGB6YwHpw2QT5HGZOvXHVW/BqlU55f1ZDDLjhmY69qC+87c54F6VNyxji6+V5BgJXJ/YEpodvrJFepN+DBcMolojD8eAC59k60+CHQXy9lboWMuy91RwO30zbBlGuUT2cRHxYzVXHF5PqKrpor4IHxyX8RHkdYtIH00mpI7spC8t2pS1JVNSk6l8COnMTMoBwKPiz8/QCRE+cc1XcD+rH4AURb9WNYVLsnFurMM5PTihBho11NCb/0UHPgLqfxWEiuo5Lmm9IcBPaD8=
