sudo: required
dist: trusty
language: node_js
node_js: '8'
os:
- linux
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
install:
- npm i
script:
- gulp
- npm run dist
before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: EGFC8COoSPPWWX4PLoACvbplCqK08Ihx/soTQlawrsbScZroFIDdh0imo7oZ10xfGRbaPT8EACkujf0XdIBKjsWGHT8ssKooPlZyUFq/XgZ8iZUmFqq8rapacYkA49CSq8ir8KKYtWFZ7ORgNPgmibo5fvz6SR8uHbHj7mdq3VmpvCuOxGbfaJZTm7qcDZcgNTM0JfRs8fkkfYCDG6jGB694RGVquHVRtpFGXGVGnwNkpx5buqbis8GmjK24gU/6M6h96Ps3inI/qqW6nIEUSkwxvNBhFKfHE9GVUEL+kplELqyVO6FZ+3NpR8ONghhfRxSQV+YFDNA0WhKvsxIuNY9NlM8FjQ5MyIh1jT2E194D3CuzQTAKMDyn27S4IxXT/ETMQ9391j86aYt96qvvGgxFezVzv6xIalBQAWy4KY+0O89GAPmX7IMdVPBjtIvmtzIkqwRNVp4soGzOYhmYCMzinuSji6Qn6SoY8LLmFBvYxv0V35mq+aar0mxoUne8VpeTGSHdGidonhfNTn8uaMCrg02/4nm5MvEkmT9s/SylE4X4WFge9BHSBB1JdiRtmASbA5oDk3gVv84xrMVwD+A59rFLrKA6laRNC4GzMzgBFO7LhpUk29LPP1SnWQYoIYqfBH9zIFrtH/fUyRudhfDx3PPOxnNUAwjRFVbEfeY=
  file:
  - dist/meistertask-electron-1.0.2-x86_64.AppImage
  - dist/meistertask-electron_1.0.2_amd64.deb
  skip_cleanup: true
  on:
    repo: ClocxHD/MeisterTask-Electron
notifications:
  slack:
    secure: CtFcAnXoiJcNIL8bDT9rWuT1vKb9Jomi//vMbdPlfZLFNJdWwvzoTNdNli4nwuhptvkfMz8L2SpDNE9rAylkNygXoUoB5SYMW174fwPza7m1LFsl5XG7kEFsz3Lj7wQDOL0zvpny2hzxVUQcqxVGphLKu7f09Q1VKtmO+dTe5dsBADtBQEL9mjDL71Bwnv3BgV+ldL2C0t3WSapm6Wr++ddHr3ivn9CRzeaUpHjqHUXjFKNQEhT5efLL4XptoMLl31n8SqRiaXl1BM45SkOu8DGPW87XV6V4WLDKt4Rwwfxsqqm8yE3D9tXw4Q/YU9lJQT9aec4Y/gnD+BCZpjSc1f3u2xoe3joEAxkfN6gHImZbv9cBJ9F+Ab+aAWiV/ttfJj+zwFm5zLPFeWGMXk0MWfD6JXJPCGB6YwHpw2QT5HGZOvXHVW/BqlU55f1ZDDLjhmY69qC+87c54F6VNyxji6+V5BgJXJ/YEpodvrJFepN+DBcMolojD8eAC59k60+CHQXy9lboWMuy91RwO30zbBlGuUT2cRHxYzVXHF5PqKrpor4IHxyX8RHkdYtIH00mpI7spC8t2pS1JVNSk6l8COnMTMoBwKPiz8/QCRE+cc1XcD+rH4AURb9WNYVLsnFurMM5PTihBho11NCb/0UHPgLqfxWEiuo5Lmm9IcBPaD8=
